FROM golang:1.25-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/judger ./cmd/judger

FROM alpine:3.19
WORKDIR /app
RUN apk add --no-cache netcat-openbsd docker-cli
COPY --from=builder /out/judger /app/judger
EXPOSE 9090
ENTRYPOINT ["/app/judger"]
