package database

import (
	"github.com/terminaloj/backend/internal/models"
)

// additionalProblems returns 47 more problems to bring total to 52, covering core algorithm categories.
func additionalProblems() []seededProblem {
	return []seededProblem{
		// ============ 数组 & 哈希表 (1006-1010) ============
		{
			ID: 1006, Title: "有效的括号", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"栈", "字符串"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 有效的括号\n\n给定一个只包含 `(`，`)`，`{`，`}`，`[`，`]` 的字符串，判断字符串是否有效。\n",
			Constraints: "1 <= |s| <= 10000",
			Editorial:   "使用栈匹配括号，遇到左括号入栈，遇到右括号检查栈顶。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "()[]{}", Expected: "true"}, {CaseNo: 2, Input: "(]", Expected: "false"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "()[]{}", Expected: "true"}, {CaseNo: 2, Input: "(]", Expected: "false"}, {CaseNo: 3, Input: "{[]}", Expected: "true", IsHidden: true}},
		},
		{
			ID: 1007, Title: "最大子数组和", Difficulty: "中等", DifficultyScore: 1300, Rating: 1300,
			Tags: models.StringSlice{"数组", "动态规划"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 最大子数组和\n\n给定整数数组，找到具有最大和的连续子数组并返回其和。\n",
			Constraints: "1 <= n <= 10^5",
			Editorial:   "Kadane算法：dp[i] = max(nums[i], dp[i-1] + nums[i])",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "5\n-2 1 -3 4 -1 2 1 -5 4", Expected: "6"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "9\n-2 1 -3 4 -1 2 1 -5 4", Expected: "6"}, {CaseNo: 2, Input: "1\n1", Expected: "1"}, {CaseNo: 3, Input: "5\n-1 -2 -3 -4 -5", Expected: "-1", IsHidden: true}},
		},
		{
			ID: 1008, Title: "三数之和", Difficulty: "中等", DifficultyScore: 1400, Rating: 1400,
			Tags: models.StringSlice{"数组", "双指针", "排序"}, Source: "TerminalOJ 原创",
			TimeLimit: 2000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 三数之和\n\n给定整数数组，找出所有和为 0 的三元组。\n",
			Constraints: "3 <= n <= 3000",
			Editorial:   "排序后双指针，注意去重。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "6\n-1 0 1 2 -1 -4", Expected: "-1 -1 2\n-1 0 1"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "6\n-1 0 1 2 -1 -4", Expected: "-1 -1 2\n-1 0 1"}, {CaseNo: 2, Input: "3\n0 0 0", Expected: "0 0 0"}},
		},
		{
			ID: 1009, Title: "接雨水", Difficulty: "困难", DifficultyScore: 1900, Rating: 1900,
			Tags: models.StringSlice{"数组", "双指针", "栈", "动态规划"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 接雨水\n\n给定 n 个非负整数表示柱子高度，计算能接多少雨水。\n",
			Constraints: "1 <= n <= 20000",
			Editorial:   "双指针法：维护左右最大高度，时间O(n)空间O(1)。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "12\n0 1 0 2 1 0 1 3 2 1 2 1", Expected: "6"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "12\n0 1 0 2 1 0 1 3 2 1 2 1", Expected: "6"}, {CaseNo: 2, Input: "6\n4 2 0 3 2 5", Expected: "9"}},
		},
		{
			ID: 1010, Title: "字母异位词分组", Difficulty: "中等", DifficultyScore: 1300, Rating: 1300,
			Tags: models.StringSlice{"哈希表", "字符串", "排序"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 字母异位词分组\n\n给定字符串数组，将字母异位词组合在一起。\n",
			Constraints: "1 <= n <= 10000",
			Editorial:   "排序后的字符串作为哈希表的key。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "3\nate eat tea", Expected: "ate tea\neat"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "3\nate eat tea", Expected: "ate tea\neat"}, {CaseNo: 2, Input: "2\na b", Expected: "a\nb"}},
		},

		// ============ 链表 (1011-1015) ============
		{
			ID: 1011, Title: "反转链表", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"链表"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 反转链表\n\n给定单链表的头节点，反转链表并返回新的头节点。\n",
			Constraints: "0 <= n <= 5000",
			Editorial:   "迭代法：使用三个指针prev, curr, next逐步反转。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "5\n1 2 3 4 5", Expected: "5 4 3 2 1"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "5\n1 2 3 4 5", Expected: "5 4 3 2 1"}, {CaseNo: 2, Input: "2\n1 2", Expected: "2 1"}, {CaseNo: 3, Input: "0", Expected: ""}},
		},
		{
			ID: 1012, Title: "环形链表", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"链表", "双指针"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 环形链表\n\n给定链表，判断是否有环。\n",
			Constraints: "0 <= n <= 10000",
			Editorial:   "快慢指针法：快指针走两步，慢指针走一步，相遇则有环。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "4\n3 2 0 -4\n1", Expected: "true"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "4\n3 2 0 -4\n1", Expected: "true"}, {CaseNo: 2, Input: "2\n1 2\n-1", Expected: "false"}},
		},
		{
			ID: 1013, Title: "合并两个有序链表", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"链表", "递归"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 合并两个有序链表\n\n将两个升序链表合并为一个新的升序链表。\n",
			Constraints: "两个链表长度之和 <= 100",
			Editorial:   "递归或迭代，比较头节点取较小者。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "3\n1 2 4\n3\n1 3 4", Expected: "1 1 2 3 4 4"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "3\n1 2 4\n3\n1 3 4", Expected: "1 1 2 3 4 4"}, {CaseNo: 2, Input: "0\n0", Expected: ""}},
		},
		{
			ID: 1014, Title: "删除链表的倒数第N个节点", Difficulty: "中等", DifficultyScore: 1200, Rating: 1200,
			Tags: models.StringSlice{"链表", "双指针"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 删除链表的倒数第N个节点\n\n给定链表，删除倒数第n个节点并返回头节点。\n",
			Constraints: "1 <= n <= 链表长度",
			Editorial:   "双指针法：快指针先走n步，然后同步走直到末尾。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "5\n1 2 3 4 5\n2", Expected: "1 2 3 5"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "5\n1 2 3 4 5\n2", Expected: "1 2 3 5"}, {CaseNo: 2, Input: "1\n1\n1", Expected: ""}},
		},
		{
			ID: 1015, Title: "LRU缓存", Difficulty: "中等", DifficultyScore: 1500, Rating: 1500,
			Tags: models.StringSlice{"链表", "哈希表", "设计"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# LRU缓存\n\n设计LRU缓存，支持get和put操作，均为O(1)时间复杂度。\n",
			Constraints: "1 <= capacity <= 3000",
			Editorial:   "哈希表+双向链表：哈希表O(1)查找，双向链表O(1)插入删除。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "2\nput 1 1\nput 2 2\nget 1\nput 3 3\nget 2", Expected: "1\n-1"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "2\nput 1 1\nput 2 2\nget 1\nput 3 3\nget 2", Expected: "1\n-1"}},
		},

		// ============ 二叉树 (1016-1020) ============
		{
			ID: 1016, Title: "二叉树的中序遍历", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"树", "栈", "递归"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 二叉树的中序遍历\n\n给定二叉树，返回其中序遍历结果。\n",
			Constraints: "节点数 <= 100",
			Editorial:   "递归：左-根-右。迭代：使用栈模拟递归。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "3\n1 null 2 3", Expected: "1 3 2"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "3\n1 null 2 3", Expected: "1 3 2"}, {CaseNo: 2, Input: "0", Expected: ""}},
		},
		{
			ID: 1017, Title: "二叉树的最大深度", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"树", "DFS", "BFS"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 二叉树的最大深度\n\n给定二叉树，返回其最大深度。\n",
			Constraints: "节点数 <= 10000",
			Editorial:   "递归：maxDepth = max(maxDepth(left), maxDepth(right)) + 1",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "3\n3 9 20 null null 15 7", Expected: "3"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "3\n3 9 20 null null 15 7", Expected: "3"}, {CaseNo: 2, Input: "1\n1 null 2", Expected: "2"}},
		},
		{
			ID: 1018, Title: "对称二叉树", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"树", "递归", "BFS"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 对称二叉树\n\n给定二叉树，检查它是否是镜像对称的。\n",
			Constraints: "节点数 <= 1000",
			Editorial:   "递归比较左子树和右子树是否镜像。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "3\n1 2 2 3 4 4 3", Expected: "true"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "3\n1 2 2 3 4 4 3", Expected: "true"}, {CaseNo: 2, Input: "3\n1 2 2 null 3 null 3", Expected: "false"}},
		},
		{
			ID: 1019, Title: "二叉树的层序遍历", Difficulty: "中等", DifficultyScore: 1200, Rating: 1200,
			Tags: models.StringSlice{"树", "BFS"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 二叉树的层序遍历\n\n给定二叉树，返回其节点值的层序遍历。\n",
			Constraints: "节点数 <= 2000",
			Editorial:   "BFS使用队列，逐层遍历。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "3\n3 9 20 null null 15 7", Expected: "3\n9 20\n15 7"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "3\n3 9 20 null null 15 7", Expected: "3\n9 20\n15 7"}},
		},
		{
			ID: 1020, Title: "验证二叉搜索树", Difficulty: "中等", DifficultyScore: 1300, Rating: 1300,
			Tags: models.StringSlice{"树", "DFS", "递归"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 验证二叉搜索树\n\n给定二叉树，判断它是否是有效的二叉搜索树。\n",
			Constraints: "节点数 <= 10000",
			Editorial:   "中序遍历检查是否严格递增，或递归传递上下界。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "2\n2 1 3", Expected: "true"}, {CaseNo: 2, Input: "5\n5 1 4 null null 3 6", Expected: "false"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "2\n2 1 3", Expected: "true"}, {CaseNo: 2, Input: "5\n5 1 4 null null 3 6", Expected: "false"}},
		},

		// ============ 二分查找 (1021-1024) ============
		{
			ID: 1021, Title: "二分查找", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"二分", "数组"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 二分查找\n\n在升序数组中查找目标值，返回索引，不存在返回-1。\n",
			Constraints: "1 <= n <= 10000",
			Editorial:   "标准二分查找模板。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "6\n-1 0 3 5 9 12\n9", Expected: "4"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "6\n-1 0 3 5 9 12\n9", Expected: "4"}, {CaseNo: 2, Input: "6\n-1 0 3 5 9 12\n2", Expected: "-1"}},
		},
		{
			ID: 1022, Title: "搜索旋转排序数组", Difficulty: "中等", DifficultyScore: 1400, Rating: 1400,
			Tags: models.StringSlice{"二分", "数组"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 搜索旋转排序数组\n\n在旋转后的升序数组中搜索目标值。\n",
			Constraints: "1 <= n <= 5000",
			Editorial:   "二分查找，先判断哪半部分有序，再决定搜索方向。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "7\n4 5 6 7 0 1 2\n0", Expected: "4"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "7\n4 5 6 7 0 1 2\n0", Expected: "4"}, {CaseNo: 2, Input: "7\n4 5 6 7 0 1 2\n3", Expected: "-1"}},
		},
		{
			ID: 1023, Title: "寻找旋转排序数组中的最小值", Difficulty: "中等", DifficultyScore: 1300, Rating: 1300,
			Tags: models.StringSlice{"二分", "数组"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 寻找旋转排序数组中的最小值\n\n在旋转后的升序数组中找到最小元素。\n",
			Constraints: "1 <= n <= 5000",
			Editorial:   "二分查找：比较mid与right，决定搜索方向。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "5\n3 4 5 1 2", Expected: "1"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "5\n3 4 5 1 2", Expected: "1"}, {CaseNo: 2, Input: "4\n2 3 4 5", Expected: "2"}},
		},
		{
			ID: 1024, Title: "在排序数组中查找元素的第一个和最后一个位置", Difficulty: "中等", DifficultyScore: 1300, Rating: 1300,
			Tags: models.StringSlice{"二分", "数组"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 在排序数组中查找元素的第一个和最后一个位置\n\n给定排序数组和目标值，找到目标值的起始和结束位置。\n",
			Constraints: "0 <= n <= 100000",
			Editorial:   "两次二分：分别查找左边界和右边界。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "6\n5 7 7 8 8 10\n8", Expected: "3 4"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "6\n5 7 7 8 8 10\n8", Expected: "3 4"}, {CaseNo: 2, Input: "6\n5 7 7 8 8 10\n6", Expected: "-1 -1"}},
		},

		// ============ 动态规划 (1025-1032) ============
		{
			ID: 1025, Title: "爬楼梯", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"动态规划", "数学"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 爬楼梯\n\n每次可以爬1或2个台阶，问有多少种不同的方法可以爬到第n阶。\n",
			Constraints: "1 <= n <= 45",
			Editorial:   "斐波那契数列：dp[n] = dp[n-1] + dp[n-2]",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "3", Expected: "3"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "3", Expected: "3"}, {CaseNo: 2, Input: "2", Expected: "2"}},
		},
		{
			ID: 1026, Title: "最长递增子序列", Difficulty: "中等", DifficultyScore: 1400, Rating: 1400,
			Tags: models.StringSlice{"动态规划", "二分"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 最长递增子序列\n\n给定整数数组，找到最长严格递增子序列的长度。\n",
			Constraints: "1 <= n <= 2500",
			Editorial:   "贪心+二分：维护tails数组，O(n log n)。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "8\n10 9 2 5 3 7 101 18", Expected: "4"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "8\n10 9 2 5 3 7 101 18", Expected: "4"}, {CaseNo: 2, Input: "4\n0 1 0 3 2 3", Expected: "4"}},
		},
		{
			ID: 1027, Title: "编辑距离", Difficulty: "中等", DifficultyScore: 1500, Rating: 1500,
			Tags: models.StringSlice{"动态规划", "字符串"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 编辑距离\n\n给定两个单词，计算将word1转换成word2所需的最少操作数。\n",
			Constraints: "0 <= len <= 500",
			Editorial:   "经典二维DP：dp[i][j]表示word1前i个字符转换为word2前j个字符的最小编辑距离。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "horse\nros", Expected: "3"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "horse\nros", Expected: "3"}, {CaseNo: 2, Input: "intention\nexecution", Expected: "5"}},
		},
		{
			ID: 1028, Title: "最长公共子序列", Difficulty: "中等", DifficultyScore: 1400, Rating: 1400,
			Tags: models.StringSlice{"动态规划", "字符串"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 最长公共子序列\n\n给定两个字符串，求它们的最长公共子序列的长度。\n",
			Constraints: "1 <= len <= 1000",
			Editorial:   "二维DP：dp[i][j] = max(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]+1 if match)",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "abcde\nace", Expected: "3"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "abcde\nace", Expected: "3"}, {CaseNo: 2, Input: "abc\nabc", Expected: "3"}, {CaseNo: 3, Input: "abc\ndef", Expected: "0"}},
		},
		{
			ID: 1029, Title: "杨辉三角", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"动态规划", "数学"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 杨辉三角\n\n给定行数，生成杨辉三角的前n行。\n",
			Constraints: "1 <= n <= 30",
			Editorial:   "每行首尾为1，中间元素等于上一行对应两个元素之和。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "5", Expected: "1\n1 1\n1 2 1\n1 3 3 1\n1 4 6 4 1"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "5", Expected: "1\n1 1\n1 2 1\n1 3 3 1\n1 4 6 4 1"}},
		},
		{
			ID: 1030, Title: "买卖股票的最佳时机", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"动态规划", "数组"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 买卖股票的最佳时机\n\n给定股票价格数组，求最大利润（只能买卖一次）。\n",
			Constraints: "1 <= n <= 100000",
			Editorial:   "维护历史最低价格，每天计算当前价格与历史最低的差值。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "7\n7 1 5 3 6 4", Expected: "5"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "6\n7 1 5 3 6 4", Expected: "5"}, {CaseNo: 2, Input: "5\n7 6 4 3 1", Expected: "0"}},
		},
		{
			ID: 1031, Title: "最大正方形", Difficulty: "中等", DifficultyScore: 1400, Rating: 1400,
			Tags: models.StringSlice{"动态规划", "矩阵"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 最大正方形\n\n在只包含0和1的矩阵中，找到只包含1的最大正方形并返回其面积。\n",
			Constraints: "1 <= m,n <= 300",
			Editorial:   "dp[i][j] = min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]) + 1",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "4 5\n1 0 1 0 0\n1 0 1 1 1\n1 1 1 1 1\n1 0 0 1 0", Expected: "4"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "4 5\n1 0 1 0 0\n1 0 1 1 1\n1 1 1 1 1\n1 0 0 1 0", Expected: "4"}},
		},
		{
			ID: 1032, Title: "完全背包问题", Difficulty: "中等", DifficultyScore: 1400, Rating: 1400,
			Tags: models.StringSlice{"动态规划", "背包"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 完全背包问题\n\n有N种物品和容量为V的背包，每种物品可无限使用，求最大价值。\n",
			Constraints: "1 <= N <= 1000, 1 <= V <= 10000",
			Editorial:   "一维DP正序遍历：dp[j] = max(dp[j], dp[j-w[i]] + v[i])",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "3 4\n2 3\n3 4\n4 5", Expected: "9"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "3 4\n2 3\n3 4\n4 5", Expected: "9"}},
		},

		// ============ 图论 (1033-1038) ============
		{
			ID: 1033, Title: "课程表", Difficulty: "中等", DifficultyScore: 1400, Rating: 1400,
			Tags: models.StringSlice{"图论", "拓扑排序", "BFS"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 课程表\n\n给定课程总数和先修关系，判断是否能完成所有课程。\n",
			Constraints: "1 <= n <= 2000",
			Editorial:   "拓扑排序：计算入度，BDFS遍历，判断是否所有节点都被访问。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "2\n1\n1 0", Expected: "true"}, {CaseNo: 2, Input: "2\n2\n1 0\n0 1", Expected: "false"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "2\n1\n1 0", Expected: "true"}, {CaseNo: 2, Input: "2\n2\n1 0\n0 1", Expected: "false"}},
		},
		{
			ID: 1034, Title: "实现Trie", Difficulty: "中等", DifficultyScore: 1400, Rating: 1400,
			Tags: models.StringSlice{"字典树", "字符串", "设计"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 实现Trie\n\n实现一个 Trie（前缀树），支持 insert、search 和 startsWith 操作。\n",
			Constraints: "1 <= 操作次数 <= 20000",
			Editorial:   "每个节点包含26个子节点指针和一个isEnd标记。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "insert apple\nsearch apple\nsearch app\nstartsWith app\ninsert app\nsearch app", Expected: "true\nfalse\ntrue\ntrue"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "insert apple\nsearch apple\nsearch app\nstartsWith app\ninsert app\nsearch app", Expected: "true\nfalse\ntrue\ntrue"}},
		},
		{
			ID: 1035, Title: "单词搜索", Difficulty: "中等", DifficultyScore: 1400, Rating: 1400,
			Tags: models.StringSlice{"图论", "回溯", "DFS"}, Source: "TerminalOJ 原创",
			TimeLimit: 2000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 单词搜索\n\n给定m×n网格和一个单词，判断该单词是否存在于网格中。\n",
			Constraints: "1 <= m,n <= 6, 1 <= len <= 15",
			Editorial:   "DFS+回溯：从每个格子开始搜索，标记已访问格子。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "3 4\nABCE\nSFCS\nADEE\nABCCED", Expected: "true"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "3 4\nABCE\nSFCS\nADEE\nABCCED", Expected: "true"}, {CaseNo: 2, Input: "3 4\nABCE\nSFCS\nADEE\nABCB", Expected: "false"}},
		},
		{
			ID: 1036, Title: "腐烂的橘子", Difficulty: "中等", DifficultyScore: 1300, Rating: 1300,
			Tags: models.StringSlice{"BFS", "图论"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 腐烂的橘子\n\n每分钟腐烂的橘子会使上下左右的新鲜橘子腐烂，求所有新鲜橘子腐烂的最小时间。\n",
			Constraints: "1 <= m,n <= 10",
			Editorial:   "多源BFS：将所有腐烂橘子入队，逐层扩展。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "3 3\n2 1 1\n1 1 0\n0 1 1", Expected: "4"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "3 3\n2 1 1\n1 1 0\n0 1 1", Expected: "4"}, {CaseNo: 2, Input: "3 3\n2 1 1\n0 1 1\n1 0 1", Expected: "-1"}},
		},
		{
			ID: 1037, Title: "克隆图", Difficulty: "中等", DifficultyScore: 1300, Rating: 1300,
			Tags: models.StringSlice{"图论", "DFS", "BFS"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 克隆图\n\n给定无向连通图的一个节点引用，返回该图的深拷贝。\n",
			Constraints: "节点数 <= 100",
			Editorial:   "DFS+BFS+哈希表：用哈希表记录已克隆的节点。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "4\n1 2 3 4\n2 4\n1 3\n1 4\n2 3", Expected: "1 2 3 4\n2 4\n1 3\n1 4\n2 3"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "4\n1 2 3 4\n2 4\n1 3\n1 4\n2 3", Expected: "1 2 3 4\n2 4\n1 3\n1 4\n2 3"}},
		},
		{
			ID: 1038, Title: "冗余连接", Difficulty: "中等", DifficultyScore: 1300, Rating: 1300,
			Tags: models.StringSlice{"并查集", "图论"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 冗余连接\n\n一棵树中添加了一条边变成图，找到这条多余的边。\n",
			Constraints: "3 <= n <= 1000",
			Editorial:   "并查集：依次加入边，如果两端已在同一集合则为多余边。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "3\n3\n1 2\n1 3\n2 3", Expected: "2 3"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "3\n3\n1 2\n1 3\n2 3", Expected: "2 3"}},
		},

		// ============ 数学 (1039-1043) ============
		{
			ID: 1039, Title: "Fizz Buzz", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"数学", "模拟"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# Fizz Buzz\n\n从1到n，3的倍数输出Fizz，5的倍数输出Buzz，15的倍数输出FizzBuzz。\n",
			Constraints: "1 <= n <= 10000",
			Editorial:   "简单模拟，注意判断顺序。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "5", Expected: "1\n2\nFizz\n4\nBuzz"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "5", Expected: "1\n2\nFizz\n4\nBuzz"}},
		},
		{
			ID: 1040, Title: "计数质数", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"数学", "埃氏筛"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 计数质数\n\n统计所有小于非负整数n的质数的数量。\n",
			Constraints: "0 <= n <= 5000000",
			Editorial:   "埃氏筛法：从2开始，将每个质数的倍数标记为合数。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "10", Expected: "4"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "10", Expected: "4"}, {CaseNo: 2, Input: "0", Expected: "0"}, {CaseNo: 3, Input: "1", Expected: "0"}},
		},
		{
			ID: 1041, Title: "Pow(x, n)", Difficulty: "中等", DifficultyScore: 1300, Rating: 1300,
			Tags: models.StringSlice{"数学", "快速幂"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# Pow(x, n)\n\n实现 pow(x, n)，即计算 x 的 n 次幂。\n",
			Constraints: "-100 < x < 100, -2^31 <= n <= 2^31-1",
			Editorial:   "快速幂：x^n = (x^2)^(n/2) if n even, x * x^(n-1) if n odd",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "2.0 10", Expected: "1024.0"}, {CaseNo: 2, Input: "2.0 -2", Expected: "0.25"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "2.0 10", Expected: "1024.0"}, {CaseNo: 2, Input: "2.0 -2", Expected: "0.25"}},
		},
		{
			ID: 1042, Title: "阶乘后的零", Difficulty: "中等", DifficultyScore: 1300, Rating: 1300,
			Tags: models.StringSlice{"数学"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 阶乘后的零\n\n给定整数n，返回n!结果中尾随零的个数。\n",
			Constraints: "0 <= n <= 10000",
			Editorial:   "统计因子5的个数：n/5 + n/25 + n/125 + ...",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "5", Expected: "1"}, {CaseNo: 2, Input: "25", Expected: "6"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "5", Expected: "1"}, {CaseNo: 2, Input: "25", Expected: "6"}},
		},
		{
			ID: 1043, Title: "Excel表列序号", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"数学", "字符串"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# Excel表列序号\n\n给定Excel列名称（如A, AB, ZY），返回其对应的列序号。\n",
			Constraints: "1 <= len <= 7",
			Editorial:   "26进制转换：result = result * 26 + (char - 'A' + 1)",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "AB", Expected: "28"}, {CaseNo: 2, Input: "ZY", Expected: "701"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "AB", Expected: "28"}, {CaseNo: 2, Input: "ZY", Expected: "701"}},
		},

		// ============ 字符串 (1044-1048) ============
		{
			ID: 1044, Title: "反转字符串", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"字符串", "双指针"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 反转字符串\n\n原地反转字符数组。\n",
			Constraints: "1 <= n <= 100000",
			Editorial:   "双指针首尾交换。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "5\nh e l l o", Expected: "o l l e h"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "5\nh e l l o", Expected: "o l l e h"}},
		},
		{
			ID: 1045, Title: "字符串中的第一个唯一字符", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"字符串", "哈希表"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 字符串中的第一个唯一字符\n\n找到字符串中第一个不重复的字符的索引。\n",
			Constraints: "1 <= n <= 100000",
			Editorial:   "两次遍历：第一次统计频次，第二次找第一个频次为1的。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "leetcode", Expected: "0"}, {CaseNo: 2, Input: "loveleetcode", Expected: "2"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "leetcode", Expected: "0"}, {CaseNo: 2, Input: "loveleetcode", Expected: "2"}},
		},
		{
			ID: 1046, Title: "有效的字母异位词", Difficulty: "简单", DifficultyScore: 800, Rating: 800,
			Tags: models.StringSlice{"字符串", "哈希表", "排序"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 有效的字母异位词\n\n判断两个字符串是否互为字母异位词。\n",
			Constraints: "1 <= n <= 50000",
			Editorial:   "统计字符频次比较，或排序后比较。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "anagram\nnagaram", Expected: "true"}, {CaseNo: 2, Input: "rat\ncar", Expected: "false"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "anagram\nnagaram", Expected: "true"}, {CaseNo: 2, Input: "rat\ncar", Expected: "false"}},
		},
		{
			ID: 1047, Title: "最长不含重复字符的子串", Difficulty: "中等", DifficultyScore: 1400, Rating: 1400,
			Tags: models.StringSlice{"字符串", "双指针", "哈希表"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 最长不含重复字符的子串\n\n给定字符串，找出不含重复字符的最长子串的长度。\n",
			Constraints: "0 <= n <= 50000",
			Editorial:   "滑动窗口+哈希表：维护窗口内无重复字符，O(n)。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "abcabcbb", Expected: "3"}, {CaseNo: 2, Input: "bbbbb", Expected: "1"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "abcabcbb", Expected: "3"}, {CaseNo: 2, Input: "bbbbb", Expected: "1"}, {CaseNo: 3, Input: "pwwkew", Expected: "3"}},
		},
		{
			ID: 1048, Title: "字符串转整数(atoi)", Difficulty: "中等", DifficultyScore: 1300, Rating: 1300,
			Tags: models.StringSlice{"字符串", "模拟"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 字符串转整数(atoi)\n\n实现atoi函数，将字符串转换为32位有符号整数。\n",
			Constraints: "0 <= len <= 200",
			Editorial:   "按规则模拟：跳空格、判断符号、读数字、处理溢出。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "42", Expected: "42"}, {CaseNo: 2, Input: "   -42", Expected: "-42"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "42", Expected: "42"}, {CaseNo: 2, Input: "   -42", Expected: "-42"}, {CaseNo: 3, Input: "4193 with words", Expected: "4193"}},
		},

		// ============ 贪心 (1049-1052) ============
		{
			ID: 1049, Title: "跳跃游戏", Difficulty: "中等", DifficultyScore: 1400, Rating: 1400,
			Tags: models.StringSlice{"贪心", "数组"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 跳跃游戏\n\n给定非负数组，判断能否到达最后一个下标。\n",
			Constraints: "1 <= n <= 10000",
			Editorial:   "贪心：维护能到达的最远位置，遍历更新。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "5\n2 3 1 1 4", Expected: "true"}, {CaseNo: 2, Input: "5\n3 2 1 0 4", Expected: "false"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "5\n2 3 1 1 4", Expected: "true"}, {CaseNo: 2, Input: "5\n3 2 1 0 4", Expected: "false"}},
		},
		{
			ID: 1050, Title: "合并区间", Difficulty: "中等", DifficultyScore: 1300, Rating: 1300,
			Tags: models.StringSlice{"贪心", "排序", "数组"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 合并区间\n\n给出一组区间，合并所有重叠的区间。\n",
			Constraints: "1 <= n <= 10000",
			Editorial:   "按左端点排序，依次合并重叠区间。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "4\n1 3\n2 6\n8 10\n15 18", Expected: "1 6\n8 10\n15 18"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "4\n1 3\n2 6\n8 10\n15 18", Expected: "1 6\n8 10\n15 18"}},
		},
		{
			ID: 1051, Title: "用最少数量的箭引爆气球", Difficulty: "中等", DifficultyScore: 1400, Rating: 1400,
			Tags: models.StringSlice{"贪心", "排序"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 用最少数量的箭引爆气球\n\n找到使得所有气球都被引爆所需的最少箭数。\n",
			Constraints: "1 <= n <= 10000",
			Editorial:   "按右端点排序，贪心选择每个区间的右端点放箭。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "4\n10 16\n2 8\n1 6\n7 12", Expected: "2"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "4\n10 16\n2 8\n1 6\n7 12", Expected: "2"}},
		},
		{
			ID: 1052, Title: "分发糖果", Difficulty: "困难", DifficultyScore: 1800, Rating: 1800,
			Tags: models.StringSlice{"贪心", "数组"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 分发糖果\n\n每个孩子至少一个糖果，评分更高的孩子比邻居获得更多糖果，求最少糖果总数。\n",
			Constraints: "1 <= n <= 20000",
			Editorial:   "两次遍历：从左到右处理递增，从右到左处理递减。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "3\n1 0 2", Expected: "5"}, {CaseNo: 2, Input: "3\n1 2 2", Expected: "4"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "3\n1 0 2", Expected: "5"}, {CaseNo: 2, Input: "3\n1 2 2", Expected: "4"}},
		},

		// ============ 回溯 (1053-1055) ============
		{
			ID: 1053, Title: "全排列", Difficulty: "中等", DifficultyScore: 1300, Rating: 1300,
			Tags: models.StringSlice{"回溯", "数组"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 全排列\n\n给定不含重复数字的数组，返回其所有可能的全排列。\n",
			Constraints: "1 <= n <= 6",
			Editorial:   "回溯法：每次选择一个未使用的数字加入排列。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "3\n1 2 3", Expected: "1 2 3\n1 3 2\n2 1 3\n2 3 1\n3 1 2\n3 2 1"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "3\n1 2 3", Expected: "1 2 3\n1 3 2\n2 1 3\n2 3 1\n3 1 2\n3 2 1"}},
		},
		{
			ID: 1054, Title: "子集", Difficulty: "中等", DifficultyScore: 1300, Rating: 1300,
			Tags: models.StringSlice{"回溯", "位运算"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 子集\n\n给定不含重复元素的整数数组，返回所有可能的子集。\n",
			Constraints: "1 <= n <= 10",
			Editorial:   "回溯法：每个元素选或不选。或位运算枚举。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "3\n1 2 3", Expected: "\n1\n2\n1 2\n3\n1 3\n2 3\n1 2 3"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "3\n1 2 3", Expected: "\n1\n2\n1 2\n3\n1 3\n2 3\n1 2 3"}},
		},
		{
			ID: 1055, Title: "电话号码的字母组合", Difficulty: "中等", DifficultyScore: 1300, Rating: 1300,
			Tags: models.StringSlice{"回溯", "字符串"}, Source: "TerminalOJ 原创",
			TimeLimit: 1000, MemoryLimit: 256, OutputLimitKB: 1024,
			Content:     "# 电话号码的字母组合\n\n给定数字字符串，返回所有它能表示的字母组合。\n",
			Constraints: "0 <= n <= 4",
			Editorial:   "回溯法：建立数字到字母的映射，逐位枚举。",
			Samples:     []models.ProblemSample{{CaseNo: 1, Input: "23", Expected: "ad ae af bd be bf cd ce cf"}},
			TestCases:   []models.ProblemTestCase{{CaseNo: 1, Input: "23", Expected: "ad ae af bd be bf cd ce cf"}},
		},
	}
}
